### ISSUE TITLE
start_hand event

### ISSUE THREAD

**Issue by closedcontour** [tjwilson90/turbo-hearts#37]
Can I get either a `start_hand` or `end_hand` event? 'start_passing' isn't good enough because of the keeper.

**Comment by tjwilson90** [comment]
how are the existing `deal` and `hand_complete` events not sufficient for this?

**Comment by closedcontour** [comment]
They are fine. I hadn't used `hand_complete` before so it wasn't on my radar. And I spaced on `deal`, it was late.
