### ISSUE TITLE
Include increasing event number in game events.

### ISSUE THREAD

**Issue by closedcontour** [tjwilson90/turbo-hearts#64]

**Comment by tjwilson90** [comment]
do you want this for taking advantage of sse last-event-ids, or for some other reason?

**Comment by closedcontour** [comment]
Mostly just to make it easy to handle a reconnect and ignore events I've already seen.

**Comment by tjwilson90** [comment]
Ok, done. I don't think this actually requires any front-end changes.

If the event stream disconnects and reconnects, you'll only receive the events you missed during the disconnect plus an end_replay event. This appears to work on the existing frontend.

If you open a game fresh you'll get all existing events plus an end_replay event (same as today).
